# Generated by Django 6.0.7 on 2026-08-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_genre_book_cover_book_genre_id_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/%Y/%m/', verbose_name='Cover'),
        ),
    ]
