# Generated by Django 6.0.7 on 2026-08-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_options_alter_book_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
