# Generated by Django 6.0.7 on 2026-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_author_author_auth_name_23b0c0_idx_and_more'),
        ('book', '0006_delete_review'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-publication_date', 'title'], name='book_book_publica_50c31e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-publication_date', 'author'], name='book_book_publica_7ee93c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-publication_date', 'genre_id'], name='book_book_publica_5e0e29_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='book_genre_name_ea47b5_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['slug'], name='book_genre_slug_e87f69_idx'),
        ),
    ]
