# Generated by Django 6.0.7 on 2026-08-04 14:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_available_copies_book_unavailable_copies_and_more'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='book.book', verbose_name='Book'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.CharField(max_length=50, verbose_name='Borrower'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='effective_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Effective return date'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Loan date'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(verbose_name='Return date'),
        ),
    ]
