# Generated by Django 6.0.7 on 2026-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_options_alter_author_biography_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='author_auth_name_23b0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['surname'], name='author_auth_surname_35eb22_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['nationality'], name='author_auth_nationa_e212a0_idx'),
        ),
    ]
