# Generated by Django 6.0.7 on 2026-07-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='subtitle')),
                ('isbn', models.CharField(max_length=50, unique=True, verbose_name='isbn')),
                ('language', models.CharField(max_length=50, verbose_name='language')),
                ('genre', models.CharField(max_length=50, verbose_name='genre')),
                ('num_pages', models.PositiveIntegerField(verbose_name='number of pages')),
                ('publication_date', models.DateField(verbose_name='publication date')),
                ('available', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='author.author', verbose_name='author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
