# Generated by Django 6.0.7 on 2026-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(blank=True, default=models.PositiveIntegerField(default=1), null=True),
        ),
    ]
