# Generated by Django 6.0.7 on 2026-08-06 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_book_alter_loan_borrower_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-loan_date'], 'verbose_name': 'loan', 'verbose_name_plural': 'loans'},
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Borrower'),
            preserve_default=False,
        ),
    ]
