# Generated by Django 6.0.7 on 2026-08-07 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_options_loan_borrower_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Borrower'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Borrower'),
        ),
    ]
