# Generated by Django 6.0.7 on 2026-08-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loan_borrower_alter_loan_borrower_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-loan_date'], 'permissions': [('view_all_loans', 'Can view all loans')], 'verbose_name': 'loan', 'verbose_name_plural': 'loans'},
        ),
    ]
