# Generated by Django 6.0.7 on 2026-08-14 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_book_book_publica_50c31e_idx_and_more'),
        ('loan', '0005_alter_loan_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['-loan_date', 'book'], name='loan_loan_loan_da_22d0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['-loan_date', 'borrower_id'], name='loan_loan_loan_da_4d289f_idx'),
        ),
    ]
