# Generated by Django 6.0.7 on 2026-08-14 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_book_book_publica_50c31e_idx_and_more'),
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['-reservation_date', 'book'], name='reservation_reserva_5506c6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['-reservation_date', 'reader'], name='reservation_reserva_f63cda_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['-reservation_date', 'is_active'], name='reservation_reserva_dc80c1_idx'),
        ),
    ]
